- id: sort
  name: Check Cargo.toml is sorted
  description: 'Ensure Cargo.toml is sorted'
  entry: cargo-sort -c -w
  language: rust
  types: [file, toml]
  files: Cargo\.toml
  pass_filenames: false
