comment_width = 90
wrap_comments = true
imports_granularity = "Crate"
newline_style = "Unix"
use_small_heuristics = "Max"
version = "Two"
fn_single_line =true
max_width = 90
group_imports = "StdExternalCrate"