[dependencies]
actix-identity = "0.2"          # Identity
actix-rt = "1.1"                # Actix runtime
actix-web = "2.0"               # Actix web
derive_more = "0.99"
env_logger = "0.7"              # logging
futures = "0.3"                 # async
jsonschema = "0.3"              # JSON schema
lazy_static = "1.4"             # runtime const evaluation
log = "0.4"                     # logging
rand = "0.7.3"                  # random value generator
serde = "1.0"                   # serialization
serde_json = "1.0"              # serialization for JSON
uuid = { version = "0.8", features = ["v4"] } # UUID

# This is a multi-line comment above a group.
# It should remain a multi-line comment after sorting.
argonautica = "0.2"  # argon2 password hashing
hex = "0.4.2"        # for encoding the bytes from hmac to a postgres TEXT field
hmac = "0.9.0"       # for api token hashing
sha2 = "0.9.1"       # for api token hashing

chrono = { version = "0.4.11", features = ["serde"] } # time
diesel = { version = "1.4.4", features = ["postgres", "chrono", "r2d2", "serde_json"] } # Database
diesel_migrations = "1.4"       # Embedding database migration
dotenv = "0.15.0"                                     # environment variables
r2d2 = "0.8"                                          # Database pooling
