[dependencies]
# The comments should prevent this short array from being put on a single line
# and they should stay on the proper feature.
first_dep = { version = "1.0", features = [
    "feat2",
    # important!
    "feat1", # other stuff
] }
# The choice of single- vs multi-line should be preserved for arrays in inline
# tables.
second_dep = { version = "1.0", features = [
    "feat2",
        "feat1",
] }
third_dep = { version = "1.0", features = [ "feat2", "feat1",  ] }

[dependencies.expanded_dep]
version = "1.0"
features = [ "feat3", "feat1", "feat2"]

[dependencies.expanded_dep_multiline]
version = "1.0"
features = [
    # This comment should stay with `feat3`.
    "feat3",
    "feat4", # This comment will end up on `feat1`.
    "feat1",
    "feat2" # This comment should stay with `feat2`.
]   # This comment should stay at the end of the array

[target.'cfg(windows)'.dependencies]
target_dep = { version = "1.0", features = [ "feat3", "feat1", "feat2"] }

[target.'cfg(windows)'.dependencies.expanded_target_dep]
version = "1.0"
features = [ "feat3", "feat1", "feat2"]
