[package]
name = "ruma"
license = "MIT"
version = "0.0.3"
edition = "2018"
foo = [
    "A",
    "N",
    "B",
    "D",
    "E"
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg","docsrs"]


[dependencies]
js_int="0.2.0"
assign="1.1.1"

ruma-api = { version = "=0.17.0-alpha.4", path = "../ruma-api", optional = true }
ruma-appservice-api = { version = "=0.2.0-alpha.3", path = "../ruma-appservice-api", optional = true }

ruma-client = "hello"
ruma-client-api = { version = "=0.10.0-alpha.3", path = "../ruma-client-api", optional = true }



ruma-federation-api = { version = "=0.1.0-alpha.2", path = "../ruma-federation-api", optional = true }
ruma-common = { version = "0.5.0", path = "../ruma-common" }
ruma-events = { version = "=0.22.0-alpha.3", path = "../ruma-events", optional = true }
ruma-identifiers = { version = "0.19.0", path = "../ruma-identifiers", features = ["serde"] }
ruma-identity-service-api = { version = "=0.1.0-alpha.1", path = "../ruma-identity-service-api", optional = true }
ruma-push-gateway-api = { version = "=0.1.0-alpha.1", path = "../ruma-push-gateway-api", optional = true }
ruma-serde = { version = "0.3.1", path = "../ruma-serde" }
ruma-signatures = { version = "0.7.0", path = "../ruma-signatures", optional = true }

[dev-dependencies]
serde = {version = "1.0.118",features = ["derive"] }
